name: Publish Mod To TS & Generate Release to GitHub

on:
  push:
    tags: "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Use checkout to publish the files in your repo
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Restore Tools
        run: |
          dotnet restore --locked-mode
          dotnet tool restore

      - name: Build & Publish to TS
        env:
          TCLI_AUTH_TOKEN: ${{ secrets.TCLI_AUTH_TOKEN }}
          PACKAGE_VERSION: ${{ github.ref_name }}
        run: |
          dotnet clean -c Release
          dotnet publish -c Release
      
      - name: Release to GitHub
        uses: softprops/action-gh-release@v2

        with:
          generate_release_notes: true
          make_latest: "true"
          files: |
            artifacts/tspublish/build/*.zip